import type { Metadata } from "next";
import "./globals.css";
import { Space_Grotesk } from "next/font/google";
import { ThemeProvider } from "./components/theme-provider"


const spaceGrotesk = Space_Grotesk( { subsets: ["latin"] } );
export const metadata: Metadata = {
  title: "ameny.online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body
        className={spaceGrotesk.className}
      >
        <ThemeProvider
            attribute="class"
            themes={['light', 'dark','hippie']}
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
